// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "nYuMNHnIEXsO97XgwMHgZBjOrbgktrqjdMvWGxDPyUq7KHJoEGbRjrZoPazJXU6Ncy3eHV";
}
}
}

